// Chain and token configuration
const CHAINS = {
  BTC: {
    id: 'BTC',
    name: 'Bitcoin',
    symbol: 'BTC',
    type: 'bitcoin',
    decimals: 8,
    confirmations: 2,
    derivationPath: "m/44'/0'/0'/0",
    api: 'https://blockstream.info/api',
    tokens: ['BTC'],
    tokenContracts: {},
  },
  ETH: {
    id: 'ETH',
    name: 'Ethereum',
    symbol: 'ETH',
    type: 'evm',
    chainId: 1,
    decimals: 18,
    confirmations: 12,
    derivationPath: "m/44'/60'/0'/0",
    rpc: 'https://ethereum.publicnode.com',
    tokens: ['ETH', 'USDT', 'USDC'],
    tokenContracts: {
      USDT: '0xdAC17F958D2ee523a2206206994597C13D831ec7',
      USDC: '0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48',
    },
  },
  BSC: {
    id: 'BSC',
    name: 'BNB Smart Chain',
    symbol: 'BNB',
    type: 'evm',
    chainId: 56,
    decimals: 18,
    confirmations: 15,
    derivationPath: "m/44'/60'/0'/0",
    rpc: 'https://bsc-rpc.publicnode.com',
    tokens: ['BNB', 'USDT', 'USDC'],
    tokenContracts: {
      USDT: '0x55d398326f99059fF775485246999027B3197955',
      USDC: '0x8AC76a51cc950d9822D68b83fE1Ad97B32Cd580d',
    },
  },
  POLYGON: {
    id: 'POLYGON',
    name: 'Polygon',
    symbol: 'MATIC',
    type: 'evm',
    chainId: 137,
    decimals: 18,
    confirmations: 20,
    derivationPath: "m/44'/60'/0'/0",
    rpc: 'https://polygon-bor-rpc.publicnode.com',
    tokens: ['MATIC', 'USDT', 'USDC'],
    tokenContracts: {
      USDT: '0xc2132D05D31c914a87C6611C10748AEb04B58e8F',
      USDC: '0x2791Bca1f2de4661ED88A30C99A7a9449Aa84174',
    },
  },
  ARBITRUM: {
    id: 'ARBITRUM',
    name: 'Arbitrum',
    symbol: 'ETH',
    type: 'evm',
    chainId: 42161,
    decimals: 18,
    confirmations: 20,
    derivationPath: "m/44'/60'/0'/0",
    rpc: 'https://arbitrum-one-rpc.publicnode.com',
    tokens: ['ETH', 'USDC', 'USDT'],
    tokenContracts: {
      USDT: '0xFd086bC7CD5C481DCC9C85ebE478A1C0b69FCbb9',
      USDC: '0xaf88d065e77c8cC2239327C5EDb3A432268e5831',
    },
  },
  TRX: {
    id: 'TRX',
    name: 'Tron',
    symbol: 'TRX',
    type: 'tron',
    decimals: 6,
    confirmations: 19,
    derivationPath: "m/44'/195'/0'/0",
    api: 'https://api.trongrid.io',
    tokens: ['TRX', 'USDT', 'USDC'],
    tokenContracts: {
      USDT: 'TR7NHqjeKQxGTCi8q8ZY4pL8otSzgjLj6t',
      USDC: 'TEkxiTehnzSmSe2XqrBj4w32RUN966rdz8',
    },
  },
  TON: {
    id: 'TON',
    name: 'TON',
    symbol: 'TON',
    type: 'ton',
    decimals: 9,
    confirmations: 1,
    api: 'https://toncenter.com/api/v2',
    tokens: ['TON', 'USDT'],
    tokenContracts: {
      USDT: 'EQCxE6mUtQJKFnGfaROTKOt1lZbDiiX1kCixRv7Nw2Id_sDs',
    },
  },
  SOL: {
    id: 'SOL',
    name: 'Solana',
    symbol: 'SOL',
    type: 'solana',
    decimals: 9,
    confirmations: 1,
    rpc: 'https://api.mainnet-beta.solana.com',
    tokens: ['SOL', 'USDC'],
    tokenContracts: {
      USDC: 'EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v',
    },
  },
  XRP: {
    id: 'XRP',
    name: 'Ripple',
    symbol: 'XRP',
    type: 'xrp',
    decimals: 6,
    confirmations: 1,
    derivationPath: "m/44'/144'/0'/0",
    api: 'https://s1.ripple.com:51234/',
    tokens: ['XRP'],
    tokenContracts: {},
  },
  LTC: {
    id: 'LTC',
    name: 'Litecoin',
    symbol: 'LTC',
    type: 'litecoin',
    decimals: 8,
    confirmations: 3,
    derivationPath: "m/44'/2'/0'/0",
    api: 'https://api.blockcypher.com/v1/ltc/main',
    tokens: ['LTC'],
    tokenContracts: {},
  },
};

// ERC-20 ABI (minimal - balanceOf + Transfer event)
const ERC20_ABI = [
  'function balanceOf(address owner) view returns (uint256)',
  'function decimals() view returns (uint8)',
  'function transfer(address to, uint256 amount) returns (bool)',
  'event Transfer(address indexed from, address indexed to, uint256 value)',
];

module.exports = { CHAINS, ERC20_ABI };
